PizzaShop.Web/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PizzaShop.Repository.ViewModels;
using PizzaShop.Service.Attributes;
using PizzaShop.Service.Interfaces;

namespace PizzaShop.Web.Controllers
{
    [CustomAuthorize("CanView", "Admin", "Manager", "Chef")]
    public class MenuController : Controller
    {
        #region Dependencies
        private readonly ILogger<MenuController> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IItemService _itemService;
        private readonly IModifiergroupService _modifiergroupService;
        private readonly IModifierService _modifierService;
        private readonly IUnitService _unitService;
        private readonly IItemModifierGroupMapService _iItemModifierGroupMapService;
        #endregion

        #region Constructor
        public MenuController(ICategoryService categoryService, IItemService itemService, IModifiergroupService modifiergroupService, IModifierService modifierService, IUnitService unitService, IItemModifierGroupMapService iItemModifierGroupMapService, ILogger<MenuController> logger)
        {
            _categoryService = categoryService;
            _itemService = itemService;
            _modifiergroupService = modifiergroupService;
            _modifierService = modifierService;
            _unitService = unitService;
            _iItemModifierGroupMapService = iItemModifierGroupMapService;
            _logger = logger;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            return View();
        }
        #endregion

        #region Add Category POST
        [CustomAuthorize("CanAddEdit", "Admin", "Manager", "Chef")]
        [HttpPost]
        public async Task<IActionResult> AddCategory(CategoryViewModel model)
        {
            if (model == null)
            {
                return Json(new { success = false, message = "Invalid request: No data received." });
            }

            if (!ModelState.IsValid)
            {
                var errors = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value?.Errors.Select(e => e.ErrorMessage).ToList()
                );

                return Json(new { success = false, errors });
            }

            try
            {
                int newCategoryId = await _categoryService.AddAsync(model);

                return Json(new
                {
                    success = true,
                    message = "Category added successfully!",
                    categoryId = newCategoryId
                });
            }
            catch (InvalidOperationException ex)
            {
                return Json(new
                {
                    success = false,
                    message = ex.Message,
                    errors = new Dictionary<string, List<string>>
            {
                { "CategoryName", new List<string> { ex.Message } }
            }
                });
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "An unexpected error occurred while adding the category." });
            }
        }
        #endregion

        public IActionResult LoadAddCategoryModal()
        {
            var model = new CategoryViewModel();
            return PartialView("_AddCategoryModal", model);
        }
        public IActionResult LoadEditCategoryModal()
        {
            var model = new CategoryViewModel();
            return PartialView("_EditCategoryModal", model);
        }

        #region Edit Category POST
        [CustomAuthorize("CanAddEdit", "Admin", "Manager", "Chef")]
        [HttpPost]
        public async Task<IActionResult> EditCategory(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value?.Errors.Select(e => e.ErrorMessage).ToList()
                );

                return Json(new
                {
                    success = false,
                    message = "Validation failed. Please fix the highlighted errors.",
                    errors
                });
            }

            try
            {
                var updated = await _categoryService.UpdateAsync(model);
                if (!updated)
                {
                    return Json(new { success = false, message = "Failed to update category." });
                }

                return Json(new { success = true, message = "Category updated successfully!" });
            }
            catch (InvalidOperationException ex)
            {
                return Json(new
                {
                    success = false,
                    message = ex.Message,
                    errors = new Dictionary<string, List<string>>
            {
                { "CategoryName", new List<string> { ex.Message } }
            }
                });
            }

            catch (KeyNotFoundException ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "An unexpected error occurred while updating the category." });
            }
        }
        #endregion


        #region GetCategoryById
        public async Task<IActionResult> GetCategoryById(int id)
        {
            var category = await _categoryService.GetCategoryByIdAsync(id);

            if (category == null)
            {
                return Json(new { success = false, message = "NO category found" });
            }
            return PartialView("_EditCategoryModal", category);
        }


        #endregion
        #region Delete Category POST
        [CustomAuthorize("CanAddEdit", "Admin", "Manager", "Chef")]
        [HttpPost]
        public async Task<IActionResult> DeleteCategory(int categoryId)
        {
            bool deleted = await _categoryService.DeleteCategory(categoryId);
            if (deleted)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        #endregion

        #region GetAllCategories
        [HttpGet]
        public async Task<IActionResult> GetAllCategories()
        {
            var categoryViewModel = await _categoryService.GetAll();
            return Json(categoryViewModel);
        }
        #endregion

        #region AddMenuItem POST
        [CustomAuthorize("CanAddEdit", "Admin", "Manager", "Chef")]
        [HttpPost]
        public async Task<IActionResult> AddMenuItem(ItemViewModel model, string ModifierGroupsJson, IFormFile? itemImage)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState
                    .Where(x => x.Value?.Errors.Count > 0)
                    .Select(x => new
                    {
                        Key = x.Key,
                        Errors = x.Value?.Errors.Select(e => e.ErrorMessage).ToList()
                    }).ToList();

                return Json(new
                {
                    success = false,
                    validationErrors = errors
                });
            }


            try
            {
                bool isDuplicate = _itemService.IsDuplicateItem(model.Itemname);
                if (isDuplicate)
                {
                    return Json(new
                    {
                        success = false,
                        message = "Item name already exists!"
                    });
                }

                var modifierGroups = JsonConvert.DeserializeObject<List<ItemModifierGroupMapViewModel>>(ModifierGroupsJson) ?? new List<ItemModifierGroupMapViewModel>();

                int itemId = await _itemService.AddMenuItem(model, itemImage);
                if (itemId <= 0)
                {
                    return Json(new
                    {
                        success = false,
                        message = "Failed to add item."
                    });
                }

                foreach (var modifierGroup in modifierGroups)
                {
                    modifierGroup.ItemId = itemId;
                    await _iItemModifierGroupMapService.AddItemModifierGroupMap(modifierGroup);
                }

                return Json(new
                {
                    success = true,
                    message = "Menu item added successfully!",
                    categoryId = model.Categoryid
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    message = "Error: " + ex.Message
                });
            }
        }

        #endregion


        #region UpdateCategoryOrder POST
        [HttpPost]
        public async Task<IActionResult> UpdateCategoryOrder([FromBody] List<int> orderedCategoryIds)
        {
            try
            {
                await _categoryService.UpdateCategoryOrderAsync(orderedCategoryIds);
                return Ok();
            }
            catch (UnauthorizedAccessException)
            {
                return BadRequest(new { success = false, message = "You are not authorized to perform this action." });
            }
        }
        #endregion


        #region GetItemById GET
        [HttpGet]
        public async Task<IActionResult> GetItemById(int id)
        {
            var item = _itemService.GetItemById(id);
            if (item == null)
            {
                return Json(new { success = false, message = "Item not found" });
            }

            var categories = await _categoryService.GetAll();

PizzaShop.Web/Views/Menu/_AddCategoryModal.cshtml
@model PizzaShop.Repository.ViewModels.CategoryViewModel

<div class="modal fade" id="addCategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="addCategoryLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="addCategoryLabel">Add Category</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form id="addCategoryForm" asp-action="AddCategory" asp-controller="Menu" method="post">
                <div class="modal-body">
                    <div class="mb-3 form-floating">
                        <input asp-for="CategoryName" class="form-control" placeholder="Name*" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                        <label asp-for="CategoryName" class="form-label">Category Name*</label>
                    </div>
                    <div class="form-floating">
                        <textarea asp-for="Description" class=" form-control"
                            placeholder="Multiple lines"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                        <label asp-for="Description" class="form-label">Description</label>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn custom-navbar-bg-color text-white d-flex align-items-center p-2">
                        Save
                    </button>
                    <button type="button" class="btn btn-outline-primary p-2" data-bs-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

PizzaShop.Web/Views/Menu/_AddModifierGroupPartial.cshtml
@model PizzaShop.Repository.ViewModels.ModifiergroupViewModel

<!-- Add ModifierGroup Modal -->
<div class="modal fade" id="addModifierGroupModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Add Modifier Group</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="addModifierGroupForm" asp-action="AddModifierGroup" asp-controller="Menu" method="post">
                <div class="modal-body">
                    <!-- Modifier Group Name -->
                    <div class="form-floating mb-3">
                        <input asp-for="ModifierGroupName" class="form-control" placeholder="Modifier Group Name"  name="ModifierGroupName">
                        <label for="ModifierGroupName">Name*</label>
                        <span asp-validation-for="ModifierGroupName" class="text-danger"></span>
                    </div>

                    <!-- Description -->
                    <div class="form-floating mb-3">
                        <textarea asp-for="Description" class="form-control" placeholder="Modifier Description" name="Description"></textarea>
                        <label for="Description">Description</label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <a class="text-decoration-none btn text-primary" id="addExistingModifiers">+ Add Existing Modifiers</a>
                    </div>

                    <div id="selectedModifiersContainer" class="mt-2"></div>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal" id="cancelModifierSelectionMain">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Ensure Validation Scripts are Included -->
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PizzaShop.Web/Views/Menu/_AddNewModifierModalPartial.cshtml
@model PizzaShop.Repository.ViewModels.ModifierSectionViewModel

<div class="modal fade" id="addModifierModalContainer" data-bs-backdrop="static" tabindex="-1" aria-hidden="true"
   data-bs-keyboard="false">
   <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
         <div class="modal-header text-muted">
            <h1 class="modal-title fs-5">Add New Modifier</h1>
            <button type="button" class="btn-close btn-close-" data-bs-dismiss="modal" aria-label="Close"></button>
         </div>

         <form id="addModifierForm" asp-action="AddModifier" asp-controller="Modifier" method="post">
            <div class="modal-body px-4">
               <div class="row">
                  <div class="col-12 col-xl-6 position-relative">
                     <div class="form-floating mb-3">
                        <div class="form-select   w-100 text-start " type="" id="modifierDropdownBtn"
                           data-bs-toggle="dropdown" aria-expanded="false">
                           Select Modifier Groups
                        </div>
                        <ul class="dropdown-menu w-100" aria-labelledby="modifierDropdownBtn">
                           <li class="p-2">
                              <input type="text" class="form-control form-control-sm" id="searchModifier"
                                 placeholder="Search...">
                           </li>
                           <li>
                              <hr class="dropdown-divider">
                           </li>
                           <div id="modifierCheckboxList" style="max-height: 200px; overflow-y: auto;">
                              @if (Model.Modifiergroups != null)
                              {
                                 @foreach (var modifierGroup in Model.Modifiergroups)
                                 { @if(modifierGroup != null){
                                    <li class="ms-2">
                                       <input type="checkbox" class="form-check-input me-2 modifier-checkbox"
                                          name="modifiercheckbox" value="@modifierGroup.ModifierGroupId"
                                          style="cursor: pointer;" id="@modifierGroup.ModifierGroupId">
                                       @modifierGroup.ModifierGroupName
                                    </li>
                                 }
                              }
                                                            }
                           </div>
                        </ul>
                        <label for="modifierDropdownBtn" style="background: none; pointer-events: none;">Modifier
                           Groups*</label>
                        <span asp-validation-for="ModifierGroupIds" class="text-danger"></span>
                        <!-- Validation error message -->
                     </div>
                  </div>
                  <div class=" col-12 col-xl-6">
                     <div class="form-floating mb-3">
                        <input asp-for="ModifierName" class="form-control form-control-sm" placeholder="Name*" />
                        <label asp-for="ModifierName"></label>
                        <span asp-validation-for="ModifierName" class="text-danger"></span>
                     </div>
                  </div>
               </div>

               <div class="row">
                  <div class="col-12 col-xl-4">
                     <div class="form-floating mb-3">
                        <input asp-for="Rate" class="form-control form-control-sm" placeholder="Rate*" />
                        <label asp-for="Rate"></label>
                        <span asp-validation-for="Rate" class="text-danger"></span>
                     </div>
                  </div>

                  <div class="col-12 col-xl-4">
                     <div class="form-floating mb-3">
                        <input asp-for="Quantity" class="form-control form-control-sm" placeholder="Quantity*" />
                        <label asp-for="Quantity"></label>
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                     </div>
                  </div>

                  <div class="col-12 col-xl-4">
                     <div class="form-floating mb-3">
                        <select asp-for="Unitid" class="form-select form-control-sm">
                           <option value="">Select a unit</option>
                           @if (Model.Units != null)
                           {
                              @foreach (var unit in Model.Units)
                              {
                                 @if (unit != null)
                                 {
                                    <option value="@unit.Unitid">@unit.Unitname</option>
                                 }
                              }
                           }
                        </select>
                        <label asp-for="Unitid"></label>
                        <span asp-validation-for="Unitid" class="text-danger"></span>

                     </div>
                  </div>
               </div>

               <div class="mb-3">
                  <div class="form-floating">
                     <textarea asp-for="Description" class="form-control form-control-sm" placeholder="Description"
                        rows="3"></textarea>
                     <label asp-for="Description"></label>
                     <span asp-validation-for="Description" class="text-danger"></span>
                  </div>
               </div>
            </div>

            <div class="modal-footer">
               <button type="submit" class="btn btn-primary">Save</button>
               <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Cancel</button>
            </div>
         </form>
      </div>
   </div>
</div>

PizzaShop.Web/Views/Menu/_CategoryPartial.cshtml
@inject PizzaShop.Service.Interfaces.IPermissionService PermissionService
@{
   var context = HttpContextAccessor?.HttpContext;
   var user = context?.User;
   var userRole = user?.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value;

   var hasMenuPermissionAddEdit = false;
   var hasMenuPermissionDelete = false;
   if (!string.IsNullOrEmpty(userRole))
   {
      hasMenuPermissionAddEdit = await PermissionService.RoleHasPermissionAsync(userRole, "CanAddEdit", 3);
      hasMenuPermissionDelete = await PermissionService.RoleHasPermissionAsync(userRole, "CanDelete", 3);
   }
}


<style>
   .category-btn:hover {
      color: #0066a7 !important;
   }

   .category-btn:hover .drag-icon {
      filter: invert(21%) sepia(99%) saturate(1065%) hue-rotate(181deg) brightness(92%) contrast(94%);
   }

   .active-category {
      color: #0066a7 !important;
   }

   .active-category .drag-icon {
      filter: invert(21%) sepia(99%) saturate(1065%) hue-rotate(181deg) brightness(92%) contrast(94%);
   }

   .category-btn .edit-category-btn,
   .category-btn .delete-category-btn {
      display: none;
   }

   .category-btn:hover .edit-category-btn,
   .category-btn:hover .delete-category-btn {
      display: inline-block;
   }

   @* .category-btn.addedit-category .edit-category-btn,
   .category-btn.addedit-category .delete-category-btn {
      display: inline-block;
   } *@

   .category-btn {
      height: 40px !important;
   }

   .sort-handle {
      cursor: grab;
   }
</style>
<script>
   function initializeCategorySortable() {
      $("#categoryList").sortable({

         update: function (event, ui) {
            var sortedIDs = $(this).sortable('toArray').map(function (id) {
               return id.split('-')[1];
            });

            $.ajax({
               url: '@Url.Action("UpdateCategoryOrder", "Menu")',
               type: 'POST',
               contentType: 'application/json',
               data: JSON.stringify(sortedIDs),
               success: function (response) {
                  toastr.success("Category order updated successfully!");
               },
               error: function (xhr, status, error) {
                  toastr.clear();
                  var response = xhr.responseJSON;
                  if (xhr.status === 401 && response && response.message) {
                     toastr.error(response.message);
                  } else if (xhr.status === 400) {
                     toastr.error("Bad Request: Please check your input.");
                  } else if (xhr.status === 500) {
                     toastr.error("Internal Server Error: Please try again later.");
                  } else {
                     toastr.error(response?.message || "An unexpected error occurred!");
                  }
               }
            });
         }
      });
   }

   $(document).ready(function () {
      initializeCategorySortable();
   });

</script>

<div class="tab-pane fade show active " id="nav-home" role="tabpanel" aria-labelledby="pills-home-tab">
   <div class="d-flex justify-content-between align-items-center px-3">
      <h4 class="custom-body-text-color text-bold">Category</h4>
      @if (hasMenuPermissionAddEdit)
      {
         <button class="btn p-0" id="openAddCategoryModal">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="#0066a7" class="bi bi-plus-square"
               viewBox="0 0 16 16">
               <path
                  d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z" />
               <path
                  d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
            </svg>
         </button>
      }
      <button type="button" class="btn-close  d-block d-xl-none" aria-label="Close" id="closeBtn"></button>
   </div>
   <div class="overflow-auto mt-3 category-wrapper">
      <ul class="list-unstyled list-group" id="categoryList">
         @{
            bool isFirstCategory = true;
         }
         @foreach (var category in Model)
         {
            string activeClass = isFirstCategory ? "active-category" : "";
            isFirstCategory = false;
            <li class="d-flex p-1 align-items-center justify-content-between category-btn btn @activeClass"
               data-id="@category.CategoryId" id="category-@category.CategoryId">
               <div class="d-flex align-items-center flex-wrap m-0 gap-2 ms-2">
                  <div class="sort-handle"><i class="fas fa-grip-vertical"></i></div> <!-- Drag Handle -->
                  <div class="text-truncate" style="max-width: 150px;">@category.CategoryName</div>
               </div>
               <div class="d-flex">
                  @if (hasMenuPermissionAddEdit)
                  {
                     <button class="edit-category-btn btn p-0 m-1" data-id="@category.CategoryId">
                        <img class="hover-img" src="~/images/icons/pen.svg" alt="edit-icon" />
                     </button>
                  }
                  @if (hasMenuPermissionDelete)
                  {
                     <button class="delete-category-btn btn p-0 m-1" data-id="@category.CategoryId">
                        <img class="hover-img" src="~/images/icons/trash.svg" alt="delete-icon" />
                     </button>
                  }
               </div>
            </li>
         }
      </ul>
   </div>
</div>

PizzaShop.Web/Views/Menu/_EditCategoryModal.cshtml
@model PizzaShop.Repository.ViewModels.CategoryViewModel

<div class="modal fade" id="editCategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="editCategoryLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="editCategoryLabel">Edit Category</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <form id="editCategoryForm" asp-action="EditCategory" asp-controller="Menu" method="post">
                <input type="hidden" asp-for="CategoryId" />

                <div class="modal-body">
                    <div class="mb-3 form-floating">
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                        <label asp-for="CategoryName" class="form-label">Category Name*</label>
                    </div>

                    <div class="mb-3 form-floating">
                        <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                        <label asp-for="Description" class="form-label">Description</label>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PizzaShop.Web/Views/Menu/_EditModifierGroupModalPartial.cshtml
@model PizzaShop.Repository.ViewModels.ModifiergroupViewModel

<div class="modal fade" id="editModifierGroupModalContainer" data-bs-backdrop="static" data-bs-keyboard="false"
    tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Update Modifier Group</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="editModifierGroupForm" asp-action="UpdateModifierGroup" asp-controller="Menu" method="post">
                <div class="modal-body">
                    <input type="hidden" asp-for="ModifierGroupId" id="EditModifiergroupid" />

                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" required name="ModifierGroupName"
                            id="EditModifiergroupname" asp-for="ModifierGroupName" placeholder="Name*" />
                        <span class="text-danger" asp-validation-for="ModifierGroupName"></span>
                        <label for="EditModifiergroupname" class="form-label">Name*</label>
                    </div>

                    <div class="form-floating  mb-3">
                        <textarea class="form-control" id="editModifierGroupDescription" name="Description"
                            asp-for="Description" placeholder="Description*" /></textarea>
                        <span class="text-danger" asp-validation-for="Description"></span>
                        <label for="editModifierGroupDescription" class="form-label">Description</label>
                    </div>

                    <div class="mb-3">
                        <a class="text-decoration-none btn text-primary" id="openExistingModifiersEdit">+ Add Existing
                            Modifiers</a>
                    </div>

                    <div id="selectedModifiersContainerEdit" class="mt-2">
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>